### PR TITLE
ci: use new token for changeset releases

### PR DESCRIPTION
**Pull request by causaly-mark**

### CODE REVIEW

**Review by stathismor — APPROVED** [review]
Curious, did you update the secrets yourself? Did we remove the GITHUB_TOKEN or is it still used?

**Comment by causaly-mark** [comment]
> Curious, did you update the secrets yourself? Did we remove the GITHUB_TOKEN or is it still used?

I have not updated the secrets yet - was awaiting access (which I have now). The GITHUB_TOKEN is likely still used by other workflows. WIll check.

**Comment by causaly-mark** [comment]
> > Curious, did you update the secrets yourself? Did we remove the GITHUB_TOKEN or is it still used?
> 
> I have not updated the secrets yet - was awaiting access (which I have now). The GITHUB_TOKEN is likely still used by other workflows. WIll check.

I don't actually see the GITHUB_TOKEN - presumably it's implicit?

**Comment by stathismor** [comment]
> > > Curious, did you update the secrets yourself? Did we remove the GITHUB_TOKEN or is it still used?
> > 
> > 
> > I have not updated the secrets yet - was awaiting access (which I have now). The GITHUB_TOKEN is likely still used by other workflows. WIll check.
> 
> I don't actually see the GITHUB_TOKEN - presumably it's implicit?

Probably. The Ci guru @causalydan will know.

**Comment by causalydan** [comment]
> > > > Curious, did you update the secrets yourself? Did we remove the GITHUB_TOKEN or is it still used?
> > > 
> > > 
> > > I have not updated the secrets yet - was awaiting access (which I have now). The GITHUB_TOKEN is likely still used by other workflows. WIll check.
> > 
> > 
> > I don't actually see the GITHUB_TOKEN - presumably it's implicit?
> 
> Probably. The Ci guru @causalydan will know.

`GITHUB_TOKEN` may be repo secret or an org secret. You'd have to ask someone with the right privileges.

**Comment by causaly-mark** [comment]
> > > > > Curious, did you update the secrets yourself? Did we remove the GITHUB_TOKEN or is it still used?
> > > > 
> > > > 
> > > > I have not updated the secrets yet - was awaiting access (which I have now). The GITHUB_TOKEN is likely still used by other workflows. WIll check.
> > > 
> > > 
> > > I don't actually see the GITHUB_TOKEN - presumably it's implicit?
> > 
> > 
> > Probably. The Ci guru @causalydan will know.
> 
> `GITHUB_TOKEN` may be repo secret or an org secret. You'd have to ask someone with the right privileges.

Of course, if we *really* want to know, @jmike could look for us (we definitely don't want to clean it up if it's an org secret).

**Pull request merged**
